site_name: predictr - Predict the Reliability
theme:
  name: material
nav:
    - Home: index.md
    - Getting started: get_started.md
    - Available classes: classes.md
    - Changelog: CHANGELOG.md

